---
# 目标系统的第一个用户
writeFiles:
  - path: /etc/skel/.config/user-dirs.conf
    content: |
      enabled=true
setPermissions:
  - path: /etc/skel
    permissions: '0755'
doAutologin: false
doReusePassword: false
autologinUser: ""
defaultUserName: "arch"
fullNameField: "你的名字"
keyboardLayout: "cn"
