# 自动全盘布局：用户只选盘，剩下交给 Calamares
# defaultFileSystemType 用 btrfs，配合下面的 subvolumes 让 snapper 能用
# （snapper 要求 / 是独立子卷，默认单卷布局下 / 是 subvol id 5，用不了）
---
defaultFileSystemType: "btrfs"
bootloader: "grub"
efiSystemPartitionName: "EFI System Partition"
efiSystemPartitionMountPoint: "/boot"
efiSystemPartitionSize: "512MiB"
efiSystemPartitionType: "fat32"
efiSystemPartitionFsLabel: "EFI"
rootPartitionName: "root"
rootPartitionMountPoint: "/"
rootPartitionSize: "100%"
rootPartitionType: "linux"
rootPartitionFsLabel: "root"
# btrfs 不建 swapfile，swap 需求由 zram 承担（post-install 里没配 zram，
# 需要的话可以在这里放开 initialSwap）
initialSwap: false
allowUnallocatedSpace: false
nameAndUuid: true

subvolumes:
    - name: "root"
      mountpoint: "/"
      options: [ "subvol=@" ]
    - name: "home"
      mountpoint: "/home"
      options: [ "subvol=@home" ]
    - name: "log"
      mountpoint: "/var/log"
      options: [ "subvol=@log" ]
    - name: "pkg"
      mountpoint: "/var/cache"
      options: [ "subvol=@pkg" ]
    - name: "swap"
      mountpoint: "/swap"
      options: [ "subvol=@swap" ]
